version: '3'
services:
  postgres:
    container_name: twitbooks_db
    image: "postgres:11.1-alpine"
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  ner:
    container_name: ner
    build: ner_service/
    ports: 
      - "5000:5000"
  web:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
