version: '3'
services:
  postgres:
    container_name: twitbooks_db
    image: "postgres:11.1-alpine"
    ports: 
      - "5433:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  ner:
    container_name: ner
    build: ner_service/
    ports: 
      - "5000:5000"
