apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.gitlab.com/paulombcosta/twitbooks/api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: .8
              memory: "1.5Gi"
          imagePullPolicy: Always
          env:
            - name: AUTH0_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: AUTH0_API_CLIENT_SECRET
            - name: AUTH0_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: AUTH0_API_CLIENT_ID
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: AUTH0_AUDIENCE
            - name: AUTH0_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: AUTH0_APP_CLIENT_ID
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: TWITTER_CONSUMER_SECRET
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: TWITTER_CONSUMER_KEY
            - name: GOODREADS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: GOODREADS_KEY
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: DB_URL
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: DB_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-env
                  key: DB_PASS
            - name: BOOK_SYNC_ENABLED
              value: "true"
            - name: TWITTER_SYNC_ENABLED
              value: "true"
            - name: ACTIVE_PROFILE
              value: prod
            - name: NER_CLIENT_URL
              value: http://ner-service
      imagePullSecrets:
        - name: gitlab-registry
